### ISSUE TITLE
state: playing

### ISSUE THREAD

**Issue by mwcz** [CommandLineHeroes/clh-bash#15]
The playing state is zoomed in on the screen

![screenshot from 2019-01-18 17-22-17](https://user-images.githubusercontent.com/364615/51415959-a36c7c00-1b45-11e9-8630-544d2075f3cf.png)

To complete this issue, create a function to "enter" the playing screen which does the following:

- [x] zoom camera in until the monitor almost fills the viewport
- [x] blank the monitor
- [x] display some help text #14
- [x] begin the timer
- [x] respond to keypresses with #1 
- [x] respond to onValidCommand and onInvalidCommand by doing the following
  * [x]  update the score
  * [x]  add command entry to the screen (scroll up older entries to make room)
- [x] at end of timer, display #20 and then move to leaderboard state

**Comment by Jared-Sprague** [comment]
yeah that's looking great.  We might have to zoom out just slightly to leave enough room for score and countdown. 

I'm uploading this for the readme:
![computer](https://user-images.githubusercontent.com/3926730/51417020-25f73a80-1b4a-11e9-8ac7-8d1ecccf3a2c.gif)

**Comment by mwcz** [comment]
Enabled python, added timer and score during gameplay.

**Comment by mwcz** [comment]
Added sfx for good commands and bad commands.  Sound for gold commands is also created but not being used yet.

**Comment by mwcz** [comment]
All the essential stuff for the play state is present, so I'm marking this done.  We've got issues already for the other play-state-related stuff like juice and golden comamnds.
